# Courtesy of Up (https://github.com/Up-Mods)

name: Upload Release Artifacts

on:
  [ pull_request, workflow_dispatch ]  
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Setup ENV
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew assemble --rerun-tasks
      - name: Publish
        uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
        with:
          github-token: ${{ github.token }}
          modrinth-id: C9UObpo7
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version: ${{ github.ref_name }}
          files: |
            **/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            **/build/libs/*-@(sources|javadoc).jar

